/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversionnumeros;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mateo
 */
public class FrmPricipal extends javax.swing.JFrame {
ImagenFondo imag = new ImagenFondo();
private void cerrar(){
        String botones[]={"Cerrar ", "Cancelar "};
        int respuesta = JOptionPane.showOptionDialog(this,"Deseas cerrar la ventana",  "Confirmacion", 0, 0, null, botones, this);
        if(respuesta==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }
    /**
     * Creates new form FrmPricipal
     */
    public FrmPricipal() {
        this.setContentPane(imag);
        initComponents();
       setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDivision = new javax.swing.JButton();
        btnMultiplica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 0, 3));
        btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Division.png"))); // NOI18N
        btnDivision.setText("         Division");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnMultiplica.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        btnMultiplica.setForeground(new java.awt.Color(255, 0, 3));
        btnMultiplica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Multi.png"))); // NOI18N
        btnMultiplica.setText("  Multiplicacion");
        btnMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 3));
        jLabel1.setText("Menu");
        jLabel1.setToolTipText("");

        btnSuma.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 0, 3));
        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Suma.png"))); // NOI18N
        btnSuma.setText("     suma");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 0, 3));
        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Resta.png"))); // NOI18N
        btnResta.setText("      Resta");
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaMouseEntered(evt);
            }
        });
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMultiplica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuma)
                .addGap(18, 18, 18)
                .addComponent(btnResta)
                .addGap(18, 18, 18)
                .addComponent(btnDivision)
                .addGap(18, 18, 18)
                .addComponent(btnMultiplica)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        (new FrmDivision(this, true)).setVisible(true);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicaActionPerformed
        // TODO add your handling code here:
        (new FrmMultiplicacion(this, true)).setVisible(true);
    }//GEN-LAST:event_btnMultiplicaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
      (new FrmSuma(this, true)).setVisible(true);

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRestaMouseEntered

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        (new FrmResta(this, true)).setVisible(true);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplica;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
class ImagenFondo extends JPanel{
private Image imagen;
@Override
public void paint(Graphics g){
    imagen = new ImageIcon(getClass().getResource("/img/Fondo.gif")).getImage();
g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
setOpaque(false);
super.paint(g);
}
    }
}